title: Superfluid Jiujitsu
email: aaron@superfluidjiujitsu.com
description: >- # this means to ignore newlines until "baseurl:"
  Strategies, concepts, drills and contraptions to help you develop Superfluid Jiujitsu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:

# Build settings
#theme: minima

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 1
paginate_path: "/page:num/"
